### ISSUE TITLE
No need for deindent method since ruby 2.3

### ISSUE THREAD

**Issue by vfonic** [mikeyhew/shopify-app-templates#5]
Not really a big issue... :)

but you can use `<<~` to deindent the code.

https://infinum.co/the-capsized-eight/multiline-strings-ruby-2-3-0-the-squiggly-heredoc

https://github.com/mikeyhew/shopify-app-templates/blob/master/polaris-rails.rb

**Comment by mikeyhew** [comment]
@vfonic thanks for the suggestion! I had no idea that existed when I wrote that code, and was pretty annoyed that it had to be so complicated. I'll change it later when I'm editing that code again.

**Comment by mikeyhew** [comment]
Thanks for the feedback. The code I wrote in #7 uses `<<~` and it's so much better :)

**Comment by vfonic** [comment]
Awesome! Thanks for getting back on this issue!

Take care.
